name: test
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: run maven
        run: mvn clean package -DskipTests

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        run: docker build -t demo .
      
      - name: test-step1
        run: echo "hola mundo"
